package invis.gl.NetworkViewer;

import invis.gl.NBNodeFactories.NetworkFactories.NetworkCaseNodeFactory;
import invis.gl.NetworkViewerNodes.NetworkCaseSetNode;
import invis.gl.NetworkVisualizationViewer.NetworkVisualizationViewer;
import invis.gl.dataprocessor.DataParser;
import invis.gl.graphvisualapi.NetworkDisplayApi.DisplayType;
import invis.gl.networkapi.NodeViewerTopComponentExtension;
import java.io.IOException;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.BeanTreeView;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.nodes.Node;
import org.openide.util.Exceptions;
import org.openide.util.Lookup;
import org.openide.util.NbBundle.Messages;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//invis.gl.NetworkViewer//NetworkViewer//EN",
autostore = false)
@TopComponent.Description(preferredID = "NetworkViewerTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "explorer", openAtStartup = false)
@ActionID(category = "Window", id = "invis.gl.NetworkViewer.NetworkViewerTopComponent")
@ActionReference(path = "Menu/Window" /*
 * , position = 333
 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_NetworkViewerAction",
preferredID = "NetworkViewerTopComponent")
@Messages(
{
    "CTL_NetworkViewerAction=NetworkViewer",
    "CTL_NetworkViewerTopComponent=NetworkViewer Window",
    "HINT_NetworkViewerTopComponent=This is a NetworkViewer window"
})
public final class NetworkViewerTopComponent extends NodeViewerTopComponentExtension implements Lookup.Provider
{

    private ExplorerManager mgr = new ExplorerManager();
    private Lookup mLookup;
    private InstanceContent mInstanceContent;

    public NetworkViewerTopComponent()
    {
        initComponents();
        this.associateLookup(ExplorerUtils.createLookup(mgr, this.getActionMap()));

        //The instanceContent and the AbstractLookup, let the Node later look itself up,
        //since it is added to the instanceContent in the RefreshNetworkNodeContents() function
        //below. This way we can put node-action code on the node itself. Take a look at NetworkCaseSetNode
        // and the functionalities for performing various sortings.
        mInstanceContent = new InstanceContent();
        mLookup = new AbstractLookup(mInstanceContent);

        setName(Bundle.CTL_NetworkViewerTopComponent());
        setToolTipText(Bundle.HINT_NetworkViewerTopComponent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        beanTreeView = new javax.swing.JScrollPane();

        beanTreeView = new BeanTreeView();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(beanTreeView, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(beanTreeView, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane beanTreeView;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened()
    {
        mDataParser = Lookup.getDefault().lookup(DataParser.class);
        this.RefreshNetworkNodeContents();
    }

    @Override
    public void ClearContents()
    {
        mInstanceContent = new InstanceContent();
        mLookup = new AbstractLookup(mInstanceContent);
        try
        {
            this.getExplorerManager().getRootContext().destroy();
        } catch (IOException ex)
        {
            Exceptions.printStackTrace(ex);
        }

    }

    public void RefreshNetworkNodeContents()
    {
        if (mDataParser.hasData())
        {

            Node trueRoot = new NetworkCaseSetNode(Children.create(
                    new NetworkCaseNodeFactory(
                    mDataParser.getNetworkCaseSet().getNetworkCaseList()),
                    true), //TODO Used to be NetworkCaseSet...
                    mDataParser.getNetworkCaseSet());
            try
            {
                mgr.getRootContext().destroy();
            } catch (IOException ex)
            {
                Exceptions.printStackTrace(ex);
            }
            mgr.setRootContext(trueRoot);
            mgr.getRootContext().setDisplayName("File: " + mDataParser.getFileName() + " - Case Size: " + mDataParser.getCaseSet().getCaseSetSize());


            mInstanceContent.add(trueRoot);

        } else
        {
            AbstractNode EmptyNode = new AbstractNode(Children.LEAF);
            EmptyNode.setName("File not loaded.");
            mgr.setRootContext(EmptyNode);
        }
    }

    @Override
    public void componentClosed()
    {
        try
        {
            mgr.getRootContext().destroy();
        } catch (IOException ex)
        {
            Exceptions.printStackTrace(ex);
        }
    }

    void writeProperties(java.util.Properties p)
    {
        p.setProperty("version", "1.0");
    }

    void readProperties(java.util.Properties p)
    {
        String version = p.getProperty("version");
    }

    /**
     * returns the lookup of the DataNetwork. Override because this implements
     * Lookup.Provider
     *
     * @return mLookup.
     */
    @Override
    public Lookup getLookup()
    {
        return (mLookup);
    }

    @Override
    public ExplorerManager getExplorerManager()
    {
        return (mgr);
    }

    @Override
    public void UpdateCurrentVV(NetworkVisualizationViewer currentVV, DisplayType type)
    {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void RefreshContents()
    {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
