package CaseGroupIdColorizer;

import invis.gl.graphviewer.NetworkDisplayTopComponent;

/**
 *
 * @author Matt
 */
public class CaseGroupIdColorizerTypeChooser extends javax.swing.JPanel
{

    /**
     * Creates new form CaseGroupIdColorizerTypeChooser
     */
    public CaseGroupIdColorizerTypeChooser()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        MultiGroupRandomModejButton = new javax.swing.JButton();
        TwoGroupGradientMapModejButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(MultiGroupRandomModejButton, org.openide.util.NbBundle.getMessage(CaseGroupIdColorizerTypeChooser.class, "CaseGroupIdColorizerTypeChooser.MultiGroupRandomModejButton.text")); // NOI18N
        MultiGroupRandomModejButton.setToolTipText(org.openide.util.NbBundle.getMessage(CaseGroupIdColorizerTypeChooser.class, "CaseGroupIdColorizerTypeChooser.MultiGroupRandomModejButton.toolTipText")); // NOI18N
        MultiGroupRandomModejButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MultiGroupRandomModejButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(TwoGroupGradientMapModejButton, org.openide.util.NbBundle.getMessage(CaseGroupIdColorizerTypeChooser.class, "CaseGroupIdColorizerTypeChooser.TwoGroupGradientMapModejButton.text")); // NOI18N
        TwoGroupGradientMapModejButton.setToolTipText(org.openide.util.NbBundle.getMessage(CaseGroupIdColorizerTypeChooser.class, "CaseGroupIdColorizerTypeChooser.TwoGroupGradientMapModejButton.toolTipText")); // NOI18N
        TwoGroupGradientMapModejButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TwoGroupGradientMapModejButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(CaseGroupIdColorizerTypeChooser.class, "CaseGroupIdColorizerTypeChooser.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MultiGroupRandomModejButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TwoGroupGradientMapModejButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MultiGroupRandomModejButton)
                    .addComponent(TwoGroupGradientMapModejButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MultiGroupRandomModejButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MultiGroupRandomModejButtonActionPerformed
    {//GEN-HEADEREND:event_MultiGroupRandomModejButtonActionPerformed
        //NetworkDisplayTopComponent x = (NetworkDisplayTopComponent) this.getParent();
        //x.ColorCaseGroupIdsRandomColors();

    }//GEN-LAST:event_MultiGroupRandomModejButtonActionPerformed

    private void TwoGroupGradientMapModejButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TwoGroupGradientMapModejButtonActionPerformed
    {//GEN-HEADEREND:event_TwoGroupGradientMapModejButtonActionPerformed
        //NetworkDisplayTopComponent x = (NetworkDisplayTopComponent) this.getParent();
        //x.ColorCaseGroupIdsTwoGroupColorMap();
        
    }//GEN-LAST:event_TwoGroupGradientMapModejButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MultiGroupRandomModejButton;
    private javax.swing.JButton TwoGroupGradientMapModejButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
